-- Fix admission_applications table structure and relationships

-- 1. Create table if it doesn't exist (based on usage seen in code)
CREATE TABLE IF NOT EXISTS admission_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  applicant_name TEXT NOT NULL,
  date_of_birth DATE NOT NULL,
  gender TEXT NOT NULL,
  parent_name TEXT NOT NULL,
  parent_phone TEXT NOT NULL,
  parent_email TEXT,
  address TEXT NOT NULL,
  previous_school TEXT,
  class_applying_for UUID, -- Should be UUID to link to classes
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Ensure class_applying_for is UUID and has Foreign Key
DO $$ 
BEGIN
  -- Check if column exists and is not UUID
  IF EXISTS (
    SELECT 1 
    FROM information_schema.columns 
    WHERE table_name = 'admission_applications' 
    AND column_name = 'class_applying_for' 
    AND data_type != 'uuid'
  ) THEN
    -- If it's text, alter it to UUID. 
    -- We use USING NULL to clear any invalid text data (like "Basic 8") that can't be cast to UUID
    ALTER TABLE admission_applications 
    ALTER COLUMN class_applying_for TYPE UUID USING NULL;
  END IF;

  -- Add Foreign Key Constraint if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 
    FROM information_schema.table_constraints 
    WHERE constraint_name = 'fk_admission_classes' 
    AND table_name = 'admission_applications'
  ) THEN
    ALTER TABLE admission_applications
    ADD CONSTRAINT fk_admission_classes
    FOREIGN KEY (class_applying_for)
    REFERENCES classes(id)
    ON DELETE SET NULL;
  END IF;
END $$;

-- 3. Enable RLS
ALTER TABLE admission_applications ENABLE ROW LEVEL SECURITY;

-- 4. Add Policies
DROP POLICY IF EXISTS "Anyone can insert applications" ON admission_applications;
CREATE POLICY "Anyone can insert applications" ON admission_applications
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Admins can view all applications" ON admission_applications;
CREATE POLICY "Admins can view all applications" ON admission_applications
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

DROP POLICY IF EXISTS "Admins can update applications" ON admission_applications;
CREATE POLICY "Admins can update applications" ON admission_applications
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );
