'use client'

import { getSupabaseBrowserClient } from './supabase-browser'
import { createUserAction } from '@/app/actions/create-user'

// Helper function to create user account with automatic retry on rate limit
export async function createUserAccount(userData: {
  email: string
  password: string
  username: string
  full_name: string
  role: 'admin' | 'teacher' | 'student'
  phone?: string
}) {
  const supabase = getSupabaseBrowserClient()
  let attempts = 0
  const maxAttempts = 3
  let lastError: any = null

  while (attempts < maxAttempts) {
    try {
      // Use Server Action to create user without signing in
      const { user } = await createUserAction({
        email: userData.email,
        password: userData.password,
        username: userData.username,
        full_name: userData.full_name,
        role: userData.role,
        phone: userData.phone
      })

      if (!user) {
        throw new Error('No user data returned from creation')
      }

      // Success! Now create/update profile
      const { error: profileError } = await supabase.from('profiles').upsert({
        id: user.id,
        email: userData.email,
        username: userData.username,
        full_name: userData.full_name,
        role: userData.role,
        phone: userData.phone || null
      }, {
        onConflict: 'id'
      })

      if (profileError) {
        throw profileError
      }

      return { success: true, userId: user.id, error: null }

    } catch (error: any) {
      lastError = error
      
      // If it's not a rate limit error, don't retry
      if (!error.message?.includes('429') && 
          !error.message?.toLowerCase().includes('rate limit') &&
          !error.message?.toLowerCase().includes('security purposes')) {
        break
      }
      
      attempts++
      if (attempts < maxAttempts) {
        const waitTime = Math.min(40000, 10000 * Math.pow(2, attempts - 1))
        console.log(`Rate limited. Retrying in ${waitTime / 1000} seconds... (Attempt ${attempts}/${maxAttempts})`)
        await new Promise(resolve => setTimeout(resolve, waitTime))
      }
    }
  }

  return { 
    success: false, 
    userId: null, 
    error: lastError?.message || 'Failed to create account after multiple attempts'
  }
}

// Helper to create teacher
export async function createTeacher(teacherData: {
  first_name: string
  middle_name?: string
  last_name: string
  email?: string
  phone?: string
  specialization?: string
  qualification?: string
  hire_date: string
  password?: string
  staff_id?: string | null
  gender?: string // Add gender optional
}) {
  const supabase = getSupabaseBrowserClient()
  console.log('📝 Creating teacher:', teacherData.first_name, teacherData.last_name)
  
  // Sanitize names for username
  const sanitizedFirst = teacherData.first_name.toLowerCase().replace(/[^a-z0-9]/g, '')
  const sanitizedLast = teacherData.last_name.toLowerCase().replace(/[^a-z0-9]/g, '')
  
  if (!sanitizedFirst || !sanitizedLast) {
    throw new Error('Invalid first or last name')
  }
  
  // Use first name + last name to avoid conflicts (e.g., fortune.nkornu)
  const username = `${sanitizedFirst}.${sanitizedLast}`
  const password = teacherData.password || 'Teacher123!'
  
  // Generate simple placeholder email for auth
  const placeholderEmail = `${username}@school.local`
  
  console.log('👤 Username:', username, '| Email:', placeholderEmail)

  // Create auth user and profile
  const { success, userId, error } = await createUserAccount({
    email: placeholderEmail,
    password,
    username,
    full_name: `${teacherData.first_name} ${teacherData.last_name}`,
    role: 'teacher',
    phone: teacherData.phone
  })

  if (!success || !userId) {
    throw new Error(error || 'Failed to create teacher account')
  }

  // Create teacher record
  const teacherRecord: any = {
    profile_id: userId,
    first_name: teacherData.first_name,
    middle_name: teacherData.middle_name || null,
    last_name: teacherData.last_name,
    phone: teacherData.phone || null,
    specialization: teacherData.specialization || null,
    qualification: teacherData.qualification || null,
    hire_date: teacherData.hire_date,
    gender: teacherData.gender || null,
    status: 'active'
  }
  
  // Add staff_id if provided (otherwise auto-generated by database)
  if (teacherData.staff_id) {
    teacherRecord.teacher_id = teacherData.staff_id
  }
  
  const { error: teacherError } = await supabase.from('teachers').insert(teacherRecord)

  if (teacherError) {
    throw teacherError
  }

  return { success: true, username, password }
}

// Helper to create student
export async function createStudent(studentData: {
  first_name: string
  middle_name?: string
  last_name: string
  email?: string
  date_of_birth: string
  gender: string
  class_id: string
  guardian_name: string
  guardian_phone: string
  guardian_email?: string
  admission_date?: string
  password?: string
}) {
  const supabase = getSupabaseBrowserClient()
  // Sanitize names for username
  const sanitizedFirst = studentData.first_name.toLowerCase().replace(/[^a-z0-9]/g, '')
  const sanitizedLast = studentData.last_name.toLowerCase().replace(/[^a-z0-9]/g, '')
  
  // Generate username: First 3 letters of firstname + Last 3 letters of lastname
  const firstPart = sanitizedFirst.substring(0, 3)
  const lastPart = sanitizedLast.substring(Math.max(0, sanitizedLast.length - 3))
  const username = `${firstPart}${lastPart}`.toLowerCase()

  // Generate password: Date of birth in DD-MM-YYYY format (e.g. 14-12-2016)
  let password = studentData.password
  if (!password && studentData.date_of_birth) {
    // Assuming date_of_birth is YYYY-MM-DD
    const parts = studentData.date_of_birth.split('-')
    if (parts.length === 3) {
      const [year, month, day] = parts
      password = `${day}-${month}-${year}`
    } else {
      password = 'Student123!' // Fallback
    }
  } else if (!password) {
    password = 'Student123!' // Fallback
  }
  
  // Generate placeholder email for auth (username-based, not actual email)
  const placeholderEmail = `${username}@school.local`

  // Create auth user and profile
  const { success, userId, error } = await createUserAccount({
    email: placeholderEmail,
    password,
    username,
    full_name: `${studentData.first_name} ${studentData.last_name}`,
    role: 'student'
  })

  if (!success || !userId) {
    throw new Error(error || 'Failed to create student account')
  }

  // Create student record
  const { error: studentError } = await supabase.from('students').insert({
    profile_id: userId,
    first_name: studentData.first_name,
    middle_name: studentData.middle_name || null,
    last_name: studentData.last_name,
    date_of_birth: studentData.date_of_birth,
    gender: studentData.gender,
    class_id: studentData.class_id,
    guardian_name: studentData.guardian_name,
    guardian_phone: studentData.guardian_phone,
    guardian_email: studentData.guardian_email || null,
    admission_date: studentData.admission_date || new Date().toISOString().split('T')[0],
    status: 'active'
  })

    if (studentError) {
    throw studentError
  }

  // Auto-assign to section with fewest students for balanced distribution
  try {
    // Get active sections with their current student counts
    const { data: activeSections } = await supabase
      .from('sections')
      .select('id')
      .eq('is_active', true)
      .order('sort_order')

    if (activeSections && activeSections.length > 0) {
      // Get current assignment counts for each active section
            const sectionCounts = await Promise.all(
        activeSections.map(async (sec: { id: string }) => {
          const { count } = await supabase
            .from('student_sections')
            .select('*', { count: 'exact', head: true })
            .eq('section_id', sec.id)
          return { id: sec.id, count: count || 0 }
        })
      )

      // Sort by count ascending, pick the section with fewest students
      sectionCounts.sort((a, b) => a.count - b.count)
      const targetSectionId = sectionCounts[0].id

      // Assign the new student
      await supabase
        .from('student_sections')
        .upsert(
          { student_id: userId, section_id: targetSectionId },
          { onConflict: 'student_id' }
        )
    }
  } catch (sectionError) {
    // Silently fail section assignment — don't block student creation
    console.warn('Failed to auto-assign section:', sectionError)
  }

  return { success: true, username, password }
}
